version: '3.7'
services:
  app:
    image: defn/home
    entrypoint: [ "sleep", "86400000" ]
    volumes:
      - .:/app/src/work/app
      - ${HOME}/.m2:/app/src/.m2
    ports:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app.loadbalancer.server.scheme=https"
      - "traefik.http.routers.app.entrypoints=https"
      - "traefik.http.routers.app.rule=Host(`app.whoa.bot`)"
  repl:
    image: defn/home
    entrypoint: [ "socat", "tcp-listen:9630,reuseaddr,fork", "tcp:app:9630" ]
    ports:
      - 9630
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.services.repl.loadbalancer.server.scheme=https"
      - "traefik.http.routers.repl.entrypoints=repl"
      - "traefik.http.routers.repl.rule=Host(`app.whoa.bot`)"
      - "traefik.http.routers.repl.middlewares=sslheader@docker"
    links:
      - app
