version: '3.7'

services:
  app:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=https"
      - "traefik.http.routers.app.rule=Host(`app.defn.sh`)"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
  repl:
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.striprepl.stripprefix.prefixes=/repl"
      - "traefik.http.middlewares.striprepl.stripprefix.forceslash=false"
      - "traefik.http.routers.repl.entrypoints=https"
      - "traefik.http.routers.repl.rule=Host(`app.defn.sh`) && PathPrefix(`/repl`)"
      - "traefik.http.routers.repl.middlewares=sslheader@docker,striprepl@docker"
      - "traefik.http.services.repl.loadbalancer.server.port=9630"
  a:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.a.entrypoints=https"
      - "traefik.http.routers.a.rule=Host(`app.whoa.bot`)"
      - "traefik.http.services.a.loadbalancer.server.port=80"

networks:
  default:
    external:
      name: kitt
