version: '3.7'
services:
  app:
    image: defn/home
    entrypoint: [ "sleep", "86400000" ]
    volumes:
      - .:/app/src/work/app
      - ${HOME}/.m2:/app/src/.m2
    ports:
      - 8080
  repl:
    image: defn/home
    restart: always
    entrypoint: [ "socat", "tcp-listen:9630,reuseaddr,fork", "tcp:app:9630" ]
    ports:
      - 9630
    links:
      - app
  a:
    image: nginx
    volumes:
      - ./release:/usr/share/nginx/html
    ports:
      - 80
  cloudflared:
    image: defn/home:${HOME_VARIANT:-latest}
    restart: always
    entrypoint: [ "/service" ]
    command: [ "cloudflared" ]
    volumes:
      - ./etc/cloudflared:/etc/cloudflared
    links:
      - a
