version: '3.7'

services:
  app:
    image: defn/home
    entrypoint: [ "sleep", "86400000" ]
    volumes:
      - cache:/app/src/.m2
      - work:/app/src/work
  repl:
    image: defn/home
    restart: always
    entrypoint: [ "socat", "tcp-listen:9630,reuseaddr,fork", "tcp:app:9630" ]
    links:
      - app
  a:
    image: nginx
    volumes:
      - ./release:/usr/share/nginx/html

volumes:
  work:
  cache:
